### ISSUE TITLE
Getting 'Invalid point compression' error from Uplink

### ISSUE THREAD

**Issue by moodmosaic** [adjoint-io/uplink-sdk-java#3]
I came across this after porting the Bouncy Castle calls to the (forthcoming) .NET SDK, surprisingly though it happens also on the Java SDK:

* First run the Java SDK's entry point `main` in *UplinkExample.java*
* Copy the generated `private.pem` and `public.pem` to the folder where the `uplink` executable is
* Run `uplink chain` for the very first time:
	```
	$ ./uplink chain
	Uplink 0.1.0
	Copyright Adjoint Inc.
	Branch   : HEAD
	Revision : bbca9d55
	Dirty    : False

	Searching for config at: config/node.config
	Using configuration: config/node.config
	Database is good.
	Could not find account at path: .uplink
	Do you want to supply your own private key (y/n): y
	Please provide the filepath to your EC private key: private.pem
	uplink: FatalError {fatalErrorMessage = "Invalid point compression."}
	$ 
	```

---

I can constantly reproduce this by reverting back the Ubuntu 64-bit 16.04.3 VM to a clean state via VMware Fusion 10's snapshot feature, so most chances are I'm *not* running into some sort of false negative...

**Comment by moodmosaic** [comment]
Just to be clear, this _isn't_ related to the forthcoming .NET SDK—I'm getting this error just by generating the keys from the Java SDK and using them in Uplink 0.1.0 `HEAD` `bbca9d55`.

This is a blocker for me, and perhaps I should probably be basing the .NET SDK in the Python one. 😕

**Comment by sdiehl** [comment]
Hi @moodmosaic I confirmed with the team, and it does seem that there is a difference in the PEM encoding between SDKs relating to upstream issues with BouncyCastle.

If you need to generate keys for testing and development use uplink itself to generate them. 

```bash
$ uplink keys authority 4
```

This will generate four private and public key files you can use:

```
auth0
├── account
├── key
└── key.pub
```

**Comment by moodmosaic** [comment]
@sdiehl, with the generated keys, I can read the public, but I'm getting this when reading the private key:

```
An unhandled exception of type 'java.security.spec.InvalidKeySpecException' occurred in
bcprov-jdk15on-158

Additional information: encoded key spec not recognized: wrong version for private key info
```

The exception is raised from inside [`ReadPrivateKey`](https://github.com/adjoint-io/uplink-sdk-java/blob/c7c06e65bb05dfb0287362a68e7744da46f22291/src/main/java/adjoint/uplink_sdk/client/Crypto.java#L117-L124).

**Comment by sdiehl** [comment]
We're going to look into this problem. There's an incompatibility in the way BouncyCastle does PEM encoding and our Haskell / Python tooling.

**Comment by moodmosaic** [comment]
@sdiehl, that'd be great. As you may tell, this one is blocking me for finishing up and releasing the .NET SDK 😢

**Comment by sdiehl** [comment]
This should be fixed in: 6f1b0f6e76ba449231a517666e22abc516110624

**Comment by moodmosaic** [comment]
I'd like to test it on Ubuntu but the download URL seems to be broken:
https://www.adjoint.io/pages/downloads.html

(Just click to download the installer on that page.)

**Comment by sdiehl** [comment]
Sorry about this, in the meantime the build artifacts are hosted here on Github:
https://github.com/adjoint-io/uplink/releases/tag/1.1

**Comment by moodmosaic** [comment]
...now I'm getting this on Ubuntu:

```
uplink: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```

I've installed it via

```bash
wget https://github.com/adjoint-io/uplink/releases/download/1.1/uplink_1.1_amd64.deb
sudo dpkg -i uplink_1.1_amd64.deb

# This was a fresh Ubuntu 16.04.3 so I also did
# sudo apt-get -f install

# I've also tried what you've previously sent me on email
# apt-get install -y libleveldb-dev leveldb-doc openssh-client expat libexpat1-dev
```

Happy to move to a ticket on https://github.com/adjoint-io/uplink/issues, but all these issues I've been facing back from the beginning wasted almost all of my spare time I've allocated to create the .NET SDK 😕

**Comment by sdiehl** [comment]
Sorry, `libpq.so` is the postgres shared library for Postgres provided by the ` libpq-dev` package for Ubuntu.

**Comment by moodmosaic** [comment]
No worries. I'll close this issue for now. I might reopen it, however, if I get back to it. Thanks for the help.
